# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.cache/wt [current_project]
set_property parent.project_path D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/D_FF.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/Main_menu.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/Student_B.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/blink_title.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/c.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/change_color.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/change_image.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk_6p25m.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk_voice.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/clock_divider.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/dff.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/find_row_col.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/increase_speed_clk.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/peak_vol.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/random_color.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_speed.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/reset.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/schoolwork.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/single_pulse.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/student_A.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/teamwork.v
  D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/NUS_year1_sem2/EE2026/Finial_project_implement/try/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
